{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./btop.nix
    ./chromium.nix
    ./cursor.nix
    ./direnv.nix
    ./eza.nix
    ./font.nix
    ./fish.nix
    ./librewolf.nix
    ./fzf.nix
    ./git.nix
    ./gtk.nix
    ./hyprland.nix
    ./hyprpaper.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./hyprsunset.nix
    ./keychain.nix
    ./kubernetes.nix
    ./mako.nix
    ./neovim.nix
    ./packages.nix
    ./qt.nix
    ./starship.nix
    ./tmux.nix
    ./tofi.nix
    ./waybar.nix
    ./wlogout.nix
    ./xdg.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
