{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./btop.nix
    ./eza.nix
    ./font.nix
    ./fish.nix
    ./firefox.nix
    ./fzf.nix
    ./ghostty.nix
    ./git.nix
    ./gtk.nix
    # ./hyprcursor.nix
    ./hyprland.nix
    ./hyprpaper.nix
    ./hyprlock.nix
    ./k9s.nix
    ./neovim.nix
    ./packages.nix
    ./qt.nix
    ./starship.nix
    ./tmux.nix
    ./tofi.nix
    ./waybar.nix
    ./xdg.nix
    ./zoxide.nix
  ];
}
